{% set version = "2.1.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-pathfindr.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pathfindR.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pathfindR.data/pathfindR.data_{{ version }}.tar.gz
  sha256: 024df34e701133a795d1b8c03c6a738460c2f868a2b8494ab17bd932fc408cde

build:
  number: 1

  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('pathfindR.data')"           # [not win]
    - "\"%R%\" -e \"library('pathfindR.data')\""  # [win]

about:
  home: https://github.com/egeulgen/pathfindR.data
  license: MIT
  summary: This is a data-only package, containing data needed to run the CRAN package 'pathfindR', a package for enrichment analysis utilizing active subnetworks. This package contains protein-protein interaction network data, data related to gene sets and example input/output data.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
extra:
  recipe-maintainers:
    - egeulgen
    - conda-forge/r

# Package: pathfindR.data
# Title: Data Package for 'pathfindR'
# Version: 2.0.0
# Authors@R: c(person("Ege", "Ulgen", role = c("cre", "cph"), email = "egeulgen@gmail.com", comment = c(ORCID = "0000-0003-2090-3621")), person("Ozan", "Ozisik", role = "aut", email = "ozanytu@gmail.com", comment = c(ORCID = "0000-0001-5980-8002")))
# Maintainer: Ege Ulgen <egeulgen@gmail.com>
# Description: This is a data-only package, containing data needed to run the CRAN package 'pathfindR', a package for enrichment analysis utilizing active subnetworks. This package contains protein-protein interaction network data, data related to gene sets and example input/output data.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 4.0)
# RoxygenNote: 7.2.3
# URL: https://github.com/egeulgen/pathfindR.data
# BugReports: https://github.com/egeulgen/pathfindR.data/issues
# NeedsCompilation: no
# Packaged: 2023-04-26 19:19:25 UTC; egeulgen
# Author: Ege Ulgen [cre, cph] (<https://orcid.org/0000-0003-2090-3621>), Ozan Ozisik [aut] (<https://orcid.org/0000-0001-5980-8002>)
# Repository: CRAN
# Date/Publication: 2023-04-27 08:30:23 UTC
